### ISSUE TITLE
Garage Door entity missing Open, Close, Stop actions

### ISSUE THREAD

**Issue by teleksterling** [markhannon/zimi-integration#13]
I believe a big was introduced in commit
#4d3e194d0d5a1cb9f38b6495a2eca72f8d3caec5

The open and close features were dropped from the garage door supported features attribute, which in turn means the there's no way from the HA interface to use the cover.open and cover.close services. Cover.stop would be handy too. I assume these three functions are never called: 

    async def async_close_cover(self, **kwargs: Any) -> None:
    async def async_open_cover(self, **kwargs: Any) -> None:
    async def async_set_cover_position(self, **kwargs: Any) -> None:

This is cover.py#L61:

        self._attr_supported_features = CoverEntityFeature.SET_TILT_POSITION

Based on this core code, [core.cover.device_action.py](https://github.com/home-assistant/core/blob/dev/homeassistant%2Fcomponents%2Fcover%2Fdevice_action.py#L79-L94) I think OPEN or TILT_OPEN should be added. 
Since there isn't a TILT_STOP, I'd suggest reverting back to non-tilt features. My door rolls up anyway :-P

**Comment by markhannon** [comment]
+ @Michael ***@***.***> please review
________________________________
From: Rick ***@***.***>
Sent: 18 January 2024 23:20
To: markhannon/zimi-integration ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [markhannon/zimi-integration] Garage Door entity missing Open, Close, Stop actions (Issue #13)


I believe a big was introduced in commit
#4d3e194d0d5a1cb9f38b6495a2eca72f8d3caec5

The open and close features were dropped from the garage door supported features attribute, which in turn means the there's no way from the HA interface to use the cover.open and cover.close services. Cover.stop would be handy too. I assume these three functions are never called:

async def async_close_cover(self, **kwargs: Any) -> None:
async def async_open_cover(self, **kwargs: Any) -> None:
async def async_set_cover_position(self, **kwargs: Any) -> None:


This is cover.py#L61:

    self._attr_supported_features = CoverEntityFeature.SET_TILT_POSITION


Based on this core code, https://github.com/home-assistant/core/blob/dev/homeassistant%2Fcomponents%2Fcover%2Fdevice_action.py#L79-L94<core.cover.device_action.py> I think OPEN or TILT_OPEN should be added.
Since there isn't a TILT_STOP, I'd suggest reverting back to non-tilt features. My door told anyway :-P

**Comment by metatraoneoz** [comment]
Any chance we get an update on this? I have the same issue and can't automate the garage door opening/closing.  
I tried to revert to older versions and it doesn't work either. Thanks for your help.

**Comment by markhannon** [comment]
Please try https://github.com/markhannon/zimi-integration/releases/tag/version_1.4.1-dev1 and tell me how it goes.   If it doesn't work then I will need to do some debugging.   The HA guys refactored the attribute code some time ago which made this stop working.

**Comment by metatraoneoz** [comment]
Hi Mark,

Thank you for that.

Done the update and seems to be working again.

Awesome stuff.

Thank you,

Pierre

**Comment by teleksterling** [comment]
Worked well for me too. 
Able to close and open, and see state reflected in app, including when controlled from outside ha. 😀
